### ISSUE TITLE
Investigate using pyodk

### ISSUE THREAD

**Issue by robsavoye** [hotosm/odkconvert#2]
In mid Sept, the organization that maintains the ODK Central server release an open source python module to use the REST API of the server. Currently odkconvert has it's own python module, but it would be preferred to use something with more community support. The new code should be investigated for Endpoint completeness.

**Comment by robsavoye** [comment]
pyodk is a very new python module for accessing an ODK Central server. Currently two other projects are using their own python code to do the same thing. Although pyodk is new, it was created by the ODK team, so we need to consider dropping our internal code that does the same thing to use the more community based code, which is open source and on github. It may be more efficient to work with the pyodk developers than maintaining our own similar code.

**Comment by ivangayton** [comment]
I looked at the PyODK code yesterday, and it looks clean and well-written, but doesn't explicitly handle all of the API endpoints that we need.

For the Field Mapping Tasking Manager workflow we need to:
- Create projects
- Create forms within projects
- Push attachement files (GeoJSON for select_from_file) for specific forms
- Publish draft forms
- Create app users
- Assign app users to forms
- Create QR codes for app users, including the general settings like basemap -> MapBox
- Detect the presence of new submissions
- Download submissions as CSV
- Download submission attachments

As far as I can see, PyODK currently doesn't support creation of app users and assignment of forms to them, pushing of attachments, or creation of QR codes. I'm not sure if it supports publishing of draft forms.

It seems like an obvious valuable contribution from our side might be too add methods for those tasks into the existing code. 

I've already implemented those calls in a primitive fashion [here](https://github.com/ivangayton/field-map-odk/blob/main/odk_fieldmap/utils/odk_requests.py)  and [here](https://github.com/ivangayton/field-map-odk/blob/main/odk_fieldmap/utils/aoi2odk.py). That's very rudimentary code, and written in a functional rather than object-oriented style, but it works, so it can be used as a guide for constructing the necessary endpoint URLs.

**Comment by robsavoye** [comment]
I also have my own ODK Central API code, initially based on your your code, but objectified and expanded. In addition I wrote an ODK client program, that uses the code in OdkCentral.py to do most of the operations, including the ones mentioned that pyodk doesn't support yet. My assumption is that although pyodk is a very new project (public this week), it will evolve. If the roadmap for pyodk supports what is needed for a CLI, then it's worth investigating it to decide if at some point it would be a better plan to use pyodk than our homegrown code.

**Comment by robsavoye** [comment]
If was decided that pyodk is still in early development, and doesn't support all the functionality needed for FMTM. Since OdkCentral.py file does implement the needed functionality, it was decided to use our own code to reduce the dependency on an external project.
